export const projects = [
  {
    id: 1,
    title: "AstraRMM Platform",
    tagline: "Early-Stage Hardware Monitoring Prototype for MSPs",
    description: "Building a proof-of-concept hardware monitoring system for Managed Service Providers. Learning end-to-end product development through iteration, testing, and pilot feedback.",
    details: [
      "Prototyping ESP32-based monitoring devices with Ethernet and PoE capability",
      "Experimenting with data collection: network uptime, temperature, and status monitoring",
      "Iterating on PCB designs for server room/network closet use cases",
      "Learning PCB layout including voltage regulation, Ethernet PHY integration, and sensor interfacing",
      "Designing 3D-printed enclosures and testing mechanical fit and thermal constraints",
      "Currently: bench testing Gen 3 prototype, working toward pilot deployment with one MSP partner",
    ],
    techStack: ["ESP32-S3", "Ethernet (W5500)", "PoE Module", "Custom PCB", "KiCad", "C/C++ Firmware", "REST APIs"],
    status: "In Progress: Gen 3 prototype, preparing for pilot testing",
    image: "/images/project-astrarmm.jpg",
  },
  {
    id: 2,
    title: "Air Quality Monitor Prototype",
    tagline: "ESP32-S3 Environmental Sensing System",
    description: "Designed and built a network-connected air quality monitoring prototype for testing in real environments. Measures CO₂, temperature, and humidity with MQTT data logging.",
    details: [
      "ESP32-S3 with dual-core processing for concurrent sensor polling and network communication",
      "SCD40 CO₂ sensor using NDIR technology, learning calibration and accuracy considerations",
      "PoE-powered design for simplified installation in pilot test locations",
      "Custom PCB layout with power supply isolation to reduce sensor noise",
      "Basic web dashboard for live data visualization and debugging",
      "3D-printed enclosure iteration—testing airflow, sensor placement, and mounting options",
      "Currently: pilot testing with 2-3 units in small commercial spaces to validate reliability",
    ],
    techStack: ["ESP32-S3", "SCD40 (CO₂)", "SHT40", "PoE", "Custom PCB", "MQTT", "KiCad"],
    status: "Pilot Testing: 2-3 units running in test environments, gathering feedback",
    image: "/images/project-airquality.jpg",
  },
  {
    id: 3,
    title: "Mesh Motion Sensor Network Prototype",
    tagline: "Low-Power Wireless Sensor Learning Project",
    description: "Building a wireless mesh network of battery-powered motion sensors to learn Thread/Zigbee protocols, low-power embedded design, and multi-node system reliability.",
    details: [
      "ESP32-C6 microcontrollers experimenting with Thread mesh networking capabilities",
      "PIR motion sensors with basic sensitivity tuning and range testing",
      "Learning deep sleep modes and power optimization—targeting long battery life (6+ months goal)",
      "Prototyping self-healing mesh concepts and debugging node communication failures",
      "Central gateway prototype aggregating sensor data via MQTT for testing",
      "Custom PCB iteration focused on minimal idle current draw and battery management",
      "Currently: lab testing 4-6 node prototype network, debugging mesh stability and power draw",
    ],
    techStack: ["ESP32-C6", "PIR Sensors", "Thread Protocol", "Custom PCB", "Low-Power Design", "Battery Management"],
    status: "In Development: 4-6 node lab prototype, working on mesh reliability and power tuning",
    image: "/images/project-motion.jpg",
  },
  {
    id: 4,
    title: "Network Monitoring Hardware Prototype",
    tagline: "Ethernet Packet Capture Learning Project",
    description: "Building a proof-of-concept network monitoring device to learn Ethernet interfacing, packet capture basics, and embedded network diagnostics. Exploring use cases for MSPs and IT troubleshooting.",
    details: [
      "ESP32 with W5500 Ethernet controller for wired network access and packet inspection learning",
      "Prototyping basic packet capture and metrics collection (latency, traffic logging)",
      "Experimenting with anomaly detection concepts and debugging false positives",
      "PoE-powered design for potential rack deployment scenarios",
      "Basic web interface for configuration and live data display (early iteration)",
      "Custom PCB layout learning signal integrity challenges for high-speed Ethernet traces",
      "Currently: bench testing prototype, validating packet capture accuracy and debugging firmware",
    ],
    techStack: ["ESP32-P4", "W5500 Ethernet", "PoE Module", "Custom PCB", "KiCad", "PCAP Protocol"],
    status: "Prototype Phase: Bench testing packet capture, refining firmware and web interface",
    image: "/images/project-network.jpg",
  },
];

export const skills = {
  "Hardware Design (Learning)": [
    "PCB Design: Schematic capture, layout basics, learning signal integrity and power distribution",
    "Tools: KiCad (primary), basic familiarity with EasyEDA",
    "Manufacturing: Design for manufacturing concepts, working with JLCPCB and PCBWay fab houses",
    "Components: ESP32 (S3, C6, P4), Ethernet PHY (W5500), PoE modules, voltage regulators",
    "Power Design: Learning buck/boost converters, LDOs, PoE concepts, and battery management",
  ],
  "Embedded Systems (Hands-On)": [
    "Microcontrollers: ESP32 ecosystem (ESP-IDF, Arduino), learning peripherals through projects",
    "Communication: I2C, SPI, UART, Ethernet basics, WiFi, BLE, experimenting with Thread/Zigbee",
    "Sensors: CO₂ (SCD40), Temperature/Humidity (SHT40, DHT22), PIR motion, ultrasonic",
    "Firmware: C/C++, learning FreeRTOS, low-power modes, basic OTA updates",
    "Protocols: MQTT, HTTP/REST basics, WebSockets, learning Modbus",
  ],
  "Prototyping & Testing": [
    "3D Printing: Enclosure design and iteration, FDM printing (PLA, PETG), learning DFA principles",
    "CAD: Fusion 360, TinkerCAD for mechanical prototypes",
    "Assembly: Through-hole and SMD soldering, hot plate reflow, hands-on debugging",
    "Testing: Multimeter, oscilloscope (learning), logic analyzer, protocol debugging with trial and error",
  ],
  "Software & Documentation": [
    "Languages: C/C++ (embedded), Python (scripting, testing), JavaScript (basic dashboards)",
    "Version Control: Git, GitHub for project tracking and iteration",
    "Documentation: Technical notes, build logs, learning to read datasheets and application notes",
    "Platforms: Linux basics (Raspberry Pi), MQTT brokers, basic web servers",
  ],
};

export const experience = [
  {
    period: "2024 - Present",
    title: "AstraRMM - Independent Hardware Project",
    company: "Self-Directed Startup Learning",
    description: "Building an early-stage hardware monitoring platform from concept to prototype",
    achievements: [
      "Designed and iterated through 3 generations of ESP32-based monitoring prototypes",
      "Created custom PCBs integrating Ethernet, PoE, and sensors—learning layout and debugging",
      "Built firmware for data collection, network communication, and basic device management",
      "Developed 3D-printed enclosure prototypes for mechanical fit testing",
      "Established pilot testing relationship with one MSP partner for real-world feedback",
    ],
    keyAchievement: "Went from zero hardware knowledge to working Gen 3 prototype in 6 months—entirely self-taught",
  },
  {
    period: "2023 - Present",
    title: "Independent Hardware Prototyping",
    company: "Self-Directed Learning Projects",
    description: "Learning embedded systems and PCB design through hands-on projects",
    achievements: [
      "Designed and fabricated 10+ custom PCBs for IoT, sensor, and network monitoring experiments",
      "Pilot tested several prototypes in small-scale real-world scenarios for validation",
      "Learned PCB design, power systems, and embedded firmware through iteration, failure, and research",
      "Built working knowledge of ESP32, Ethernet interfacing, PoE concepts, and sensor integration",
      "Developed debugging skills through hands-on troubleshooting and online community support",
    ],
    keyAchievement: "Built functional hardware prototypes with no formal training—learning entirely through practice",
  },
  {
    period: "2022 - 2023",
    title: "Self-Taught Embedded Systems Foundations",
    company: "Hands-On Learning Journey",
    description: "Building foundational skills through progressively complex projects",
    achievements: [
      "Completed 20+ ESP32 learning projects from basic sensors to multi-device networked prototypes",
      "Learned I2C, SPI, UART, Ethernet, and wireless protocols through trial, error, and documentation",
      "Built understanding of power design, voltage regulation, and PCB layout basics",
      "Transitioned from breadboard prototypes to custom PCBs with functional, testable results",
    ],
    keyAchievement: "Progressed from Arduino blink tutorials to designing working custom PCBs in 18 months",
  },
];
