export const projects = [
  {
    id: 1,
    title: "AstraRMM Platform",
    tagline: "Production-Ready Hardware Monitoring for MSPs",
    description: "Production-ready hardware monitoring platform for MSPs, combining PoE devices, secure telemetry, and centralized reporting for server rooms and network closets.",
    details: [
      "ESP32-S3 monitoring device with Ethernet + PoE for reliable field power",
      "Secure device telemetry: uptime, temperature, power status, and network health",
      "OTA firmware updates and remote configuration for fleet maintenance",
      "Custom PCB with voltage regulation, Ethernet PHY, and sensor integration",
      "Tamper-resistant enclosure designed for rack/closet deployment",
      "Pilot deployments in MSP environments with real-world validation",
    ],
    techStack: ["ESP32-S3", "Ethernet (W5500)", "PoE Module", "Custom PCB", "KiCad", "C/C++ Firmware", "REST APIs"],
    status: "Pilot Deployment: Production hardware in MSP environments",
    image: "/images/project-astrarmm-1.png",
  },
  {
    id: 2,
    title: "Air Quality Monitor",
    tagline: "SEN55 PoE Air Sensor with Tamper Resistance",
    description: "Application-ready air quality monitor built around the Sensirion SEN55, PoE-powered, tamper-resistant, and equipped with a 6-axis IMU for enclosure integrity.",
    details: [
      "SEN55 multi-sensor (PM/VOC/NOx/temperature/humidity) for commercial environments",
      "PoE power and Ethernet for single-cable installs",
      "Tamper-resistant enclosure with 6-axis IMU for movement/tamper detection",
      "Calibrated airflow path and sensor placement for stable readings",
      "MQTT/REST telemetry with local buffering and health checks",
      "Designed for continuous operation and remote maintenance",
    ],
    techStack: ["ESP32-P4 Ethernet", "Sensirion SEN55", "PoE", "6-Axis IMU", "Custom PCB", "MQTT", "KiCad"],
    status: "Production-Ready: Application-grade air sensor package",
    image: "/images/project-airquality-5.png",
    slides: [
      { src: "/images/project-airquality-5.png", alt: "Air quality monitor photo 5" },
      { src: "/images/project-airquality-2.png", alt: "Air quality monitor photo 2" },
      { src: "/images/project-airquality-3.png", alt: "Air quality monitor photo 3" },
      { src: "/images/project-airquality-4.png", alt: "Air quality monitor photo 4" },
      { src: "/images/project-airquality-1.png", alt: "Air quality monitor photo 1" },
    ],
  },
  {
    id: 3,
    title: "Mesh Motion Sensor Network",
    tagline: "Low-Power mmWave Presence Mesh",
    description: "Wireless mesh of mmWave presence sensors for occupancy and security, optimized for low power and reliable multi-node coverage.",
    details: [
      "ESP32-C3 nodes with Thread/Zigbee mesh networking",
      "Dual LDC2410C mmWave presence sensors for reliable detection",
      "AHT20 + MBP280 for temperature, humidity, and pressure telemetry",
      "Deep-sleep tuning for multi-month battery life",
      "Self-healing mesh with automatic node discovery",
      "Gateway aggregates data via MQTT/REST",
    ],
    techStack: ["ESP32-C3", "LDC2410C mmWave", "AHT20", "MBP280", "Thread Protocol", "Custom PCB"],
    status: "Production-Ready Pilot: 4–6 node mesh running continuously",
    image: "/images/project-motion-2.png",
    slides: [
      { src: "/images/project-motion-2.png", alt: "Motion sensor device photo 2" },
      { src: "/images/project-motion-1.png", alt: "Motion sensor device photo 1" },
      { src: "/images/project-motion-3.png", alt: "Motion sensor device photo 3" },
    ],
  },
  {
    id: 4,
    title: "Network Monitoring Hardware",
    tagline: "Packet Capture & Diagnostics Appliance",
    description: "Purpose-built network monitoring appliance delivering packet capture, latency metrics, and anomaly detection for MSPs and IT teams.",
    details: [
      "ESP32-S3 Ethernet device for inline or tap-based monitoring",
      "Real-time packet capture, latency tracking, and traffic profiling",
      "PoE-powered for rack deployment with minimal cabling",
      "Hardened enclosure and secure device management",
      "Web interface for configuration, alerts, and live diagnostics",
      "Validated in live network troubleshooting scenarios",
    ],
    techStack: ["ESP32-S3 Ethernet", "W5500 Ethernet", "PoE Module", "Custom PCB", "KiCad", "PCAP Protocol"],
    status: "Production-Ready Pilot: Used for diagnostics in live networks",
    image: "/images/project-network-3.png",
    slides: [
      { src: "/images/project-network-3.png", alt: "Network monitor device photo 3" },
      { src: "/images/project-network-2.png", alt: "Network monitor device photo 2" },
      { src: "/images/project-network-1.png", alt: "Network monitor device photo 1" },
    ],
  },
  {
    id: 5,
    title: "Taskchrono.com",
    tagline: "Work-in-Progress Productivity Platform",
    description: "Taskchrono.com is a work-in-progress platform for time tracking, task management, and client-ready reporting for service teams.",
    details: [
      "Time tracking, task timelines, and activity history in a single dashboard",
      "Client-ready reporting with exportable summaries",
      "Team roles, permissions, and audit trails for accountability",
      "Fast search, tagging, and filters for large project lists",
      "Roadmap focused on integrations and workflow automation",
    ],
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "SaaS", "Reporting", "API"],
    status: "Work in Progress: MVP in active development",
    image: "/images/project-taskchrono-1.png",
  },
];

export const skills = {
  "Hardware Design": [
    "PCB Design: Schematic capture, layout, signal integrity, and power distribution",
    "Tools: KiCad (primary), EasyEDA",
    "Manufacturing: Design for manufacturing (DFM), JLCPCB, PCBWay",
    "Components: ESP32 (S3, C3), Ethernet PHY (W5500), PoE modules, voltage regulators",
    "Power Design: Buck/boost converters, LDOs, PoE, battery management",
  ],
  "Embedded Systems": [
    "Microcontrollers: ESP32 ecosystem (ESP-IDF, Arduino), deep peripheral knowledge",
    "Communication: I2C, SPI, UART, Ethernet, WiFi, BLE, Thread/Zigbee",
    "Sensors: CO₂ (SCD40), Temperature/Humidity (SHT40, DHT22), mmWave presence, ultrasonic",
    "Firmware: C/C++, FreeRTOS, low-power modes, OTA updates",
    "Protocols: MQTT, HTTP/REST, WebSockets, Modbus",
  ],
  "Prototyping & Testing": [
    "3D Printing: Enclosure design and iteration, FDM printing (PLA, PETG), design for assembly",
    "CAD: Fusion 360, TinkerCAD for mechanical prototypes",
    "Assembly: Through-hole and SMD soldering, hot plate reflow, debugging",
    "Testing: Multimeter, oscilloscope, logic analyzer, protocol debugging",
  ],
  "Software & Documentation": [
    "Languages: C/C++ (embedded), Python (scripting, testing), JavaScript (dashboards)",
    "Version Control: Git, GitHub for project tracking and release workflows",
    "Documentation: Technical specs, build guides, datasheets",
    "Platforms: Linux (Raspberry Pi), MQTT brokers, web servers",
  ],
};

export const experience = [
  {
    period: "2024 - Present",
    title: "Founder & Hardware Engineer",
    company: "AstraRMM",
    description: "Leading hardware product development from concept to pilot deployments",
    achievements: [
      "Delivered three generations of ESP32-based monitoring hardware",
      "Designed custom PCBs integrating Ethernet, PoE, and multi-sensor telemetry",
      "Built firmware for secure data collection, remote management, and OTA updates",
      "Developed production-ready enclosures for rack and closet deployment",
      "Established pilot deployments with MSP partners for real-world validation",
    ],
    keyAchievement: "Shipped Gen 3 production-ready hardware and launched MSP pilot deployments",
  },
  {
    period: "2023 - Present",
    title: "Independent Hardware Projects",
    company: "Self-Directed",
    description: "Delivering production-ready prototypes across IoT, sensor, and network monitoring",
    achievements: [
      "Designed and fabricated 10+ custom PCBs for IoT and monitoring use cases",
      "Pilot tested prototypes in real environments for reliability validation",
      "Built production-focused power, Ethernet, PoE, and sensor integration workflows",
      "Implemented firmware for telemetry, configuration, and field diagnostics",
      "Developed structured test plans and documentation for repeatable builds",
    ],
    keyAchievement: "Delivered field-ready prototypes with repeatable manufacturing workflows",
  },
  {
    period: "2022 - 2023",
    title: "Embedded Systems Foundations",
    company: "Hands-On Development",
    description: "Built core embedded skills through progressively complex projects",
    achievements: [
      "Completed 20+ ESP32 projects from basic sensors to multi-device networked prototypes",
      "Implemented I2C, SPI, UART, Ethernet, and wireless protocols across devices",
      "Designed power systems, voltage regulation, and PCB layouts",
      "Transitioned from breadboards to custom PCBs with testable results",
    ],
    keyAchievement: "Progressed from entry-level builds to custom PCB designs in 18 months",
  },
];
