export const projects = [
  {
    id: 1,
    title: "AstraRMM Platform",
    tagline: "Hardware-Powered RMM for MSPs",
    description: "Building a complete hardware and software platform for Managed Service Providers to monitor client networks, server health, and environmental conditions remotely.",
    details: [
      "Custom ESP32-based monitoring devices with Ethernet and PoE capability",
      "Real-time data collection: network uptime, server metrics, temperature, power status",
      "Designed for deployment in server rooms and network closets",
      "PCB design includes voltage regulation, Ethernet PHY, sensor integration, and secure communication",
      "Production-ready enclosures designed for rack mounting and field installation",
    ],
    techStack: ["ESP32-S3", "Ethernet (W5500)", "PoE Module", "Custom PCB", "KiCad", "C/C++ Firmware", "REST APIs"],
    status: "Active Startup Project",
    image: "/images/project-astrarmm.jpg",
  },
  {
    id: 2,
    title: "Industrial Air Quality Monitor",
    tagline: "ESP32-S3 Environmental Monitoring System",
    description: "Designed and built a network-connected air quality monitoring device for industrial and commercial spaces. Measures CO₂, temperature, and humidity with real-time alerts and logging.",
    details: [
      "ESP32-S3 with dual-core processing for sensor data and network communication",
      "SCD40 CO₂ sensor with NDIR technology for accurate readings",
      "PoE-powered for easy installation without local power sources",
      "Custom PCB with isolated power design to prevent sensor interference",
      "Web dashboard for real-time monitoring and historical data analysis",
      "Designed 3D-printed enclosure optimized for airflow and sensor accuracy",
    ],
    techStack: ["ESP32-S3", "SCD40 (CO₂)", "SHT40", "PoE", "Custom PCB", "MQTT", "KiCad"],
    status: "Deployed in 3 commercial locations for continuous monitoring",
    image: "/images/project-airquality.jpg",
  },
  {
    id: 3,
    title: "Distributed Motion Sensor Network",
    tagline: "Low-Power Mesh Sensor System",
    description: "Created a wireless mesh network of motion sensors for building automation and security monitoring, optimized for battery life and reliability.",
    details: [
      "ESP32-C6 microcontrollers with Thread/Zigbee support for mesh networking",
      "PIR motion sensors with adjustable sensitivity and range",
      "Deep sleep optimization achieving 6+ months battery life on coin cells",
      "Self-healing mesh network with automatic node discovery",
      "Central gateway aggregates data and provides HTTP/MQTT interface",
      "Custom PCBs designed for minimal power consumption",
    ],
    techStack: ["ESP32-C6", "PIR Sensors", "Thread Protocol", "Custom PCB", "Low-Power Design", "Battery Management"],
    status: "12-node network deployed and running reliably for 4+ months",
    image: "/images/project-motion.jpg",
  },
  {
    id: 4,
    title: "Network Monitoring Hardware",
    tagline: "Custom PCB for Real-Time Packet Analysis",
    description: "Built a dedicated hardware device for network monitoring and packet inspection, designed for MSPs and IT teams who need reliable traffic analysis tools.",
    details: [
      "ESP32 with Ethernet controller for direct network tap access",
      "Real-time packet capture and analysis",
      "Detects network anomalies, measures latency, and logs traffic patterns",
      "PoE-powered for deployment in network racks without additional power",
      "Web interface for configuration and live monitoring",
      "Custom PCB with optimized signal integrity for high-speed Ethernet",
    ],
    techStack: ["ESP32-P4", "W5500 Ethernet", "PoE Module", "Custom PCB", "KiCad", "PCAP Protocol"],
    status: "Prototype completed, used for diagnostics in 5+ network deployments",
    image: "/images/project-network.jpg",
  },
];

export const skills = {
  "Hardware Design": [
    "PCB Design: Schematic capture, layout, signal integrity, power distribution",
    "Tools: KiCad, Altium (basic), EasyEDA",
    "Manufacturing: Design for manufacturing (DFM), working with JLCPCB, PCBWay",
    "Components: ESP32 (S3, C6, P4), Ethernet PHY (W5500, LAN8720), PoE modules, voltage regulators",
    "Power Design: Buck/boost converters, LDOs, PoE power systems, battery management",
  ],
  "Embedded Systems": [
    "Microcontrollers: ESP32 ecosystem (ESP-IDF, Arduino), deep understanding of peripherals",
    "Communication: I2C, SPI, UART, Ethernet, WiFi, BLE, Thread/Zigbee",
    "Sensors: CO₂ (SCD40), Temperature/Humidity (SHT40, DHT22), PIR motion, ultrasonic",
    "Firmware: C/C++, FreeRTOS, low-power optimization, OTA updates",
    "Protocols: MQTT, HTTP/REST, WebSockets, Modbus",
  ],
  "Prototyping & Manufacturing": [
    "3D Printing: Enclosure design, FDM printing (PLA, PETG), design for assembly",
    "CAD: Fusion 360, TinkerCAD for mechanical design",
    "Assembly: Through-hole and SMD soldering, reflow (hot plate), debugging",
    "Testing: Multimeter, oscilloscope (basic), logic analyzer, protocol debugging",
  ],
  "Software & Tools": [
    "Languages: C/C++, Python (scripting, testing), JavaScript (dashboards)",
    "Version Control: Git, GitHub",
    "Documentation: Technical specs, datasheets, build guides",
    "Platforms: Linux (Raspberry Pi), MQTT brokers, web servers",
  ],
};

export const experience = [
  {
    period: "2024 - Present",
    title: "Founder & Hardware Engineer",
    company: "AstraRMM",
    description: "Building a hardware-powered RMM platform from scratch",
    achievements: [
      "Designed and prototyped 3 generations of ESP32-based monitoring devices",
      "Created production PCBs with Ethernet, PoE, and multi-sensor integration",
      "Built firmware stack for real-time monitoring, remote management, and secure communication",
      "Developed 3D-printed enclosures for rack-mount and field deployment",
      "Partnered with MSPs for beta testing and real-world validation",
    ],
    keyAchievement: "Went from concept to working prototype in 6 months with zero formal training",
  },
  {
    period: "2023 - Present",
    title: "Independent Hardware Projects",
    company: "Self-Directed Learning",
    description: "Hands-on learning through real builds",
    achievements: [
      "Designed 10+ custom PCBs across IoT, sensor, and network monitoring projects",
      "Deployed monitoring systems in commercial and industrial environments",
      "Learned PCB design, power systems, and embedded firmware through iteration and problem-solving",
      "Built proficiency with ESP32, Ethernet systems, PoE, and sensor integration",
      "Developed skills in schematic capture, layout, manufacturing, and debugging",
    ],
    keyAchievement: "Created production-ready devices with no formal engineering background",
  },
  {
    period: "2022 - 2023",
    title: "Self-Taught Embedded Systems",
    company: "Intensive Learning & Prototyping",
    description: "Foundation building through hands-on projects",
    achievements: [
      "Completed 20+ ESP32 projects ranging from simple sensors to complex networked devices",
      "Learned I2C, SPI, Ethernet, and wireless communication protocols",
      "Built understanding of power design, voltage regulation, and PCB layout",
      "Transitioned from breadboards to custom PCBs with reliable, deployable results",
    ],
    keyAchievement: "Progressed from Arduino blink sketches to production PCB designs in 18 months",
  },
];
